title = "OrderedDictionary"
gitSourceBranch = "main"

apiCategories = [
	"Constructors",
	"Methods"
]

[home]
enabled = false
includeReadme = true

[docusaurus]
baseUrl = "/ordered-dictionary-luau"

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"