[package]
name = "egomoose/ordered-dictionary"
description = "A dictionary that remembers the order in which keys were first inserted."
repository = "https://github.com/EgoMoose/ordered-dictionary-luau"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"